### ISSUE TITLE
Allow custom classes to be added to nodes, links

### ISSUE THREAD

**Issue by pmackay** [ricklupton/d3-sankey-diagram#1]
What do you think about there being a customisation method to support adding CSS classes to nodes and links? This should (I think) then allow the image styling to be performed in CSS rather than via color settings in the data config.

Great work on extending the original D3 sankey lib :)

**Comment by ricklupton** [comment]
Thanks for the suggestion! So are you thinking of adding another method like 
[linkColor](https://github.com/ricklupton/d3-sankey-diagram/wiki#linkColor) -- something like linkClass?

I don't think this should replace linkColor, since you might want to generate the color depending on values in the data, but for some uses I can imaging this being useful.

There is already something undocumented which does this for nodes [in node.js](https://github.com/ricklupton/d3-sankey-diagram/blob/master/src/node.js#L231). This could be exposed with a nodeClass accessor.

**Comment by pmackay** [comment]
Exactly, something like `linkClass` as an additional method, to set CSS classes rather than colours directly.

**Comment by ricklupton** [comment]
I'll revisit this once the update to d3 v4 is done (#4)

**Comment by ricklupton** [comment]
Version 0.6 of d3-sankey-diagram is now based on d3 v4. I haven't added this feature as it's pretty simple to do this using d3 directly: [here is an example](https://bl.ocks.org/ricklupton/5ca474581ec21588f2357fd1c3a5c1dd).

However if there is an example of a situation when having this built in would be useful I'm happy to reconsider or accept a PR.
